server:
  port: 8001
spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:localhost:8888
  jpa:
    show-sql : true
    defer-datasource-initialization: true
  datasource:
    url : jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    instances:
      fail-test:
        maxAttempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


