server:
  port: 8081
spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/currency
    username: root
    password: PasswordChanged@7
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    instances:
      fail-test:
        maxAttempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true

